export class ChartSong {
    Name: string = "";
    Artist?: string = undefined;
    ArtistText?: string = undefined;
    Charter?: string = undefined;
    Album?: string = undefined;
    Year?: string = undefined;
    Offset?: number = undefined;
    CountOff?: string = undefined;
    GuitarVol?: number = undefined;
    BandVol?: number = undefined;
    HoPo?: number = undefined;
    Singer?: string = undefined;
    OriginalArtist?: boolean = undefined;
    Resolution: number = 0;
    Player2?: string = undefined;
    Difficulty?: number = undefined;
    PreviewStart?: number = undefined;
    PreviewEnd?: number = undefined;
    Genre?: string = undefined;
    MediaType?: string = undefined;
    MusicStream?: string = undefined;
    GuitarStream?: string = undefined;
    BassStream?: string = undefined;
    RhythmStream?: string = undefined;
    DrumStream?: string = undefined;
}
